/**
 * Composable to manage Payrexx checkout URL access.
 * Provides centralized checkout flow entry point.
 */
export const usePayrexxCheckout = () => {
  const { getCheckoutUrl: getCheckoutUrlFromApi } = useSubscriptionApi()

  /**
   * Gets the Payrexx checkout URL generated by the backend.
   */
  const getCheckoutUrl = async (): Promise<string> => {
    const { checkoutUrl } = await getCheckoutUrlFromApi()
    return checkoutUrl
  }

  /**
   * Opens checkout in new tab/window.
   */
  const openCheckout = async (): Promise<void> => {
    const url = await getCheckoutUrl()
    window.open(url, '_blank', 'noreferrer')
  }

  /**
   * Navigates to checkout (same tab).
   */
  const navigateToCheckout = async (): Promise<void> => {
    const url = await getCheckoutUrl()
    window.location.href = url
  }

  return {
    getCheckoutUrl,
    openCheckout,
    navigateToCheckout
  }
}
